### ISSUE TITLE
watchnixtoons2

### ISSUE THREAD

**Issue by Katkiller316** [doko-desuka/plugin.video.watchnixtoons2#22]
I have an issue with dubbed anime kodi gives me an error after selecting the dubbed anime option
I have put the error log here if you can help    thanks for the previous quick reply

2019-10-13 21:44:52.064 T:7924   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Generic catalog scrape fail: /dubbed-anime-list
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.watchnixtoons2\Default.py", line 4, in <module>
                                                main() # See bottom of Plugin.py.
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.watchnixtoons2\Lib\Plugin.py", line 1296, in main
                                                globals()[params.get('action', 'actionMenu')](params) # Defaults to 'actionMenu()'.
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.watchnixtoons2\Lib\Plugin.py", line 106, in actionCatalogMenu
                                                catalog = getCatalogProperty(params)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.watchnixtoons2\Lib\Plugin.py", line 995, in getCatalogProperty
                                                catalog = _rebuildCatalog()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.watchnixtoons2\Lib\Plugin.py", line 975, in _rebuildCatalog
                                                catalog = func(params)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.watchnixtoons2\Lib\Plugin.py", line 956, in makeGenericCatalog
                                                raise Exception('Generic catalog scrape fail: ' + params['path'])
                                            Exception: Generic catalog scrape fail: /dubbed-anime-list
                                            -->End of Python script error report<--
2019-10-13 21:44:52.176 T:1084   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.watchnixtoons2/?action=actionCatalogMenu&path=%2fdubbed-anime-list
2019-10-13 21:44:52.185 T:11056   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.watchnixtoons2/?action=actionCatalogMenu&path=%2fdubbed-anime-list) failed

hope to hear from you soon

**Comment by doko-desuka** [comment]
That Dubbed Anime category also works in here, and played an episode. That error happens when it fails to load the web page.  

So I'm unable to reproduce it, sorry. Are you using the LibreELEC OS on your device? Some users reported problems after updating this OS.

**Comment by Katkiller316** [comment]
i'm using a windows 10 laptop if that is what you mean

**Comment by doko-desuka** [comment]
Is Dubbed Anime the only category that doesn't work?  
What add-on version are you using? (you can see that after right-clicking on the add-on icon and choosing Information)  
Have you tried uninstalling and reinstalling it?  
Did it ever work before, and what happened before it stopped working?   

Can you [access this link here with a browser](https://www.watchcartoononline.io/dubbed-anime-list) on that same laptop? This is the page the add-on is trying to load, if it works on your browser then the problem is somehow inside Kodi. But again, it's working in here so we know that the add-on code is fine.

**Comment by Katkiller316** [comment]
hi thanks for your reply

no category works
im using version 0.3.5
if tried uninstalling and reinstalling the addon and kodi 
ive even tried just having the addon and kodi nothing else
i used to work fine but just stopped working 
i can access the website fine on my laptop it does have a capcha screen 

hope these answer you questions    many thanks for helping

**Comment by doko-desuka** [comment]
> it does have a captcha screen  

Well there you have it. The captcha hides the page content, so the add on can't find the content it needs.  
Maybe this happens because of your geographical location, your internet provider or something else that is triggering the captcha protection.  

As a test, are you able to [access this link](https://www.wcoanimedub.tv/dubbed-anime-list) without a captcha? (Use a private tab so cookies don't interfere w/ the result)
